Repository graphops/graphcast-sdk, pull requests merged in 2023-05, with the labels that each got.

#202 update release process and script
  .auto-changelog
  .github/dependabot.yml
  .github/workflows/main.yml
  changelog.md
  contributing.md
  pull_request_template.md
  scripts/release.sh
Labels: documentation, chore

#200 refactor: move config parsing to Radio
  examples/ping-pong/src/config.rs
  examples/ping-pong/src/main.rs
  src/config.rs
  src/graphcast_agent/mod.rs
  src/lib.rs
Labels: refactor

#206 chore: release v0.1.2
  Cargo.lock
  Cargo.toml
  changelog.md
  scripts/release.sh
Labels: chore

#207 release v0.1.2
  .auto-changelog
  .github/dependabot.yml
  .github/workflows/main.yml
  Cargo.toml
  changelog.md
  contributing.md
  examples/ping-pong/Cargo.toml
  examples/ping-pong/src/config.rs
  examples/ping-pong/src/main.rs
  pull_request_template.md
  scripts/release.sh
  src/config.rs
  src/graphcast_agent/mod.rs
  src/lib.rs
Labels: chore

#212 chore: v0.2.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  scripts/release.sh
  src/graphcast_agent/mod.rs
Labels: chore

#218 logger formats
  Cargo.lock
  Cargo.toml
  examples/ping-pong/src/config.rs
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
  src/graphql/client_graph_node.rs
  src/graphql/client_network.rs
  src/graphql/client_registry.rs
  src/lib.rs
Labels: feat

#221 refactor: update query for new registry subgraph schema
  README.md
  src/graphql/client_registry.rs
  src/graphql/query_registry.graphql
  src/graphql/schema_registry.graphql
Labels: feat

#222 feat: add Telegram bot support
  Cargo.lock
  Cargo.toml
  src/bots.rs
  src/graphcast_agent/waku_handling.rs
Labels: feat, rust

#225 refactor: change radio_name to be String
  examples/ping-pong/src/main.rs
  src/graphcast_agent/mod.rs
Labels: refactor
