Repository graphops/graphcast-sdk, pull requests merged in 2023-02, with the labels that each got.

#69 refactor: improve error handling
  Cargo.toml
  examples/ping-pong/src/main.rs
  src/gossip_agent/message_typing.rs
  src/gossip_agent/mod.rs
  src/gossip_agent/waku_handling.rs
  src/graphql/client_network.rs
  src/lib.rs
  src/tree_to_txt.rs
Labels: type:refactor

#85 refactor: rename agent to graphcast
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
  src/graphql/client_registry.rs
  src/lib.rs
Labels: type:refactor

#86 Update registry query
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphql/client_network.rs
  src/graphql/client_registry.rs
  src/graphql/query_registry.graphql
  src/graphql/schema_registry.graphql
  src/lib.rs
Labels: type:refactor

#92 refactor: remove redundant log
  Cargo.lock
  Cargo.toml
  src/graphcast_agent/message_typing.rs
Labels: type:refactor

#93 dependency path to git commit of waku-bindings 0.0.1-beta3
  Cargo.lock
  Cargo.toml
Labels: dependencies

#97 Feat: Block hash from indexing statuses query
  .env.example
  .versionrc.json
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
  src/graphql/client_graph_node.rs
  src/graphql/mod.rs
  src/graphql/query_block_hash_from_number.graphql
  src/graphql/query_indexing_statuses.graphql
  src/graphql/schema_graph_node.graphql
  src/lib.rs
Labels: type:feature

#100 content topic poll and update
  Cargo.lock
  Cargo.toml
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
Labels: type:feature

#103 refactor: check topics upon receive
  Cargo.lock
  Cargo.toml
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
Labels: type:enhancement

#107 feat: auto resolve dns url by pubsub topic
  examples/ping-pong/src/main.rs
  src/graphcast_agent/waku_handling.rs
  src/lib.rs
Labels: type:feature

#108 refactor: log filters and new error variants
  Cargo.lock
  Cargo.toml
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
  src/graphql/client_network.rs
  src/graphql/client_registry.rs
  src/lib.rs
Labels: type:refactor

#109 fix: unique peer message filter
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
Labels: type:bug

#111 fix: explicit indexer address check
  examples/ping-pong/src/main.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
Labels: type:bug

#113 Fix: Additional sender id check
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/waku_handling.rs
Labels: type:bug
