Repository graphops/graphcast-sdk, pull requests merged in 2023-01, with the labels that each got.

#34 feat: peer discovery with consistent DNS enrtree url
  .gitignore
  Cargo.toml
  src/gossip_agent/mod.rs
  src/gossip_agent/waku_handling.rs
  src/lib.rs
  src/records_to_tree.rs
Labels: type:feature

#33 Add ping-pong Radio
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  examples/ping-pong/Cargo.toml
  examples/ping-pong/src/main.rs
  examples/poi-crosschecker/Cargo.toml
  examples/poi-crosschecker/src/attestations.rs
  examples/poi-crosschecker/src/graphql/mod.rs
  examples/poi-crosschecker/src/graphql/query_proof_of_indexing.graphql
  examples/poi-crosschecker/src/graphql/schema_proof_of_indexing.graphql
  examples/poi-crosschecker/src/main.rs
  examples/poi-crosschecker/src/utils.rs
  src/gossip_agent/mod.rs
  src/gossip_agent/waku_handling.rs
Labels: type:feature

#39 Allow users to configure subgraph urls and subtopics
  .env.example
  .gitignore
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  examples/ping-pong/Cargo.toml
  examples/ping-pong/src/main.rs
  src/gossip_agent/message_typing.rs
  src/gossip_agent/mod.rs
  src/gossip_agent/waku_handling.rs
Labels: type:feature

#63 Refactor topics and Gossip agent
  examples/ping-pong/src/main.rs
  src/gossip_agent/message_typing.rs
  src/gossip_agent/mod.rs
  src/gossip_agent/waku_handling.rs
  src/graphql/client_network.rs
  src/lib.rs
  src/tree_to_txt.rs
Labels: type:enhancement

#61 refactor: improve boot node logic
  Cargo.lock
  examples/ping-pong/src/main.rs
  src/gossip_agent/mod.rs
  src/gossip_agent/waku_handling.rs
  src/lib.rs
Labels: type:refactor
