Repository graphops/graphcast-sdk, pull requests merged in 2023-03, with the labels that each got.

#119 feat: automated release script
  .github/dependabot.yml
  .github/release.yml
  Cargo.lock
  Cargo.toml
  scripts/release.sh
Labels: type:feature, type:documentation

#133 basic args validation and improve logs
  Cargo.lock
  Cargo.toml
  examples/ping-pong/src/main.rs
  src/config.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
  src/graphql/client_graph_node.rs
  src/graphql/client_network.rs
  src/graphql/client_registry.rs
  src/lib.rs
Labels: feat, refactor

#137 chore: publish v0.0.14
  Cargo.lock
  Cargo.toml
  src/bots.rs
Labels: chore

#140 feat: mnemonics allowed, refactor network config
  examples/ping-pong/src/main.rs
  src/config.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphql/client_graph_node.rs
  src/lib.rs
  src/networks.rs
Labels: feat, refactor

#154 fix: waku node setup with filter protocol only
  pull_request_template.md
  src/graphcast_agent/waku_handling.rs
Labels: bug

#163 refactor: replace bool prometheus_metrics with u16 metrics_port
  src/config.rs
Labels: refactor
