Repository graphops/graphcast-sdk, pull requests merged in 2023-04, with the labels that each got.

#176 feat: add metrics_host to config
  src/config.rs
  src/graphcast_agent/mod.rs
Labels: feat

#180 Revert "feat: auto approve and merge pr by dependabot (#149)"
  .github/workflows/auto-approve-n-merge.yml
Labels: chore

#175 chore: add e2e test helpers
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/graphcast_agent/mod.rs
Labels: rust

#182 Create GraphcastMessage GraphQL Output type and API server config
  Cargo.lock
  Cargo.toml
  examples/ping-pong/src/types.rs
  src/config.rs
  src/graphcast_agent/message_typing.rs
  src/graphcast_agent/mod.rs
  src/graphcast_agent/waku_handling.rs
  src/lib.rs
Labels: feat

#193 docs: new release process and changelog script
  .auto-changelog
  changelog.md
  contributing.md
  scripts/release.sh
Labels: documentation

#194 Release v0.1.0
  .auto-changelog
  Cargo.lock
  Cargo.toml
  changelog.md
  contributing.md
  scripts/release.sh
Labels: chore

#201 release topics lock
  src/graphcast_agent/mod.rs
Labels: bug
